Vektor --> 1 dimensional array\
Matriks --> 2 dimensional array

In [1]:
import numpy as np

### vektor

In [2]:
#define vector on code
v = np.array([1,2,3])

In [3]:
v.shape

(3,)

### Matriks

In [11]:
#define matrix on code
M = np.array([
    [1,2],
    [3,4],
    [5,6]
    ])

M

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
M.shape

(3, 2)

### Akses elemen matrix

##### akses spesifik baris

In [15]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
A[1]

array([4, 5, 6])

##### akses spesifik baris dan kolom tertentu

In [23]:
A[1][2]

6

In [24]:
A[1,2]

6

##### Akses spesifik kolom

In [27]:
A[:,2]

array([3, 6, 9])

### Types os Matrix

In [29]:
# Square Matrix
x = np.array([
    [4,9,2],
    [3,6,7],
    [8,1,6]
])

x

array([[4, 9, 2],
       [3, 6, 7],
       [8, 1, 6]])

In [36]:
# Upper Triangle Matrix
# np.triu(x)

np.triu(x)

array([[4, 9, 2],
       [0, 6, 7],
       [0, 0, 6]])

In [37]:
# Lower triangle Matrix
# np.tril(x)
np.tril(x)

array([[4, 0, 0],
       [3, 6, 0],
       [8, 1, 6]])

In [35]:
# Diagonal Matrix
# np.diag(x)

np.diag(x)

array([4, 6, 6])

In [38]:
np.diag(np.diag(x))

array([[4, 0, 0],
       [0, 6, 0],
       [0, 0, 6]])

In [40]:
# Identity Matrix
# np.eye(shape)

np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### **Operasi Atirmetika**
- penjumlahan
- pengurangan
- pembagian
- perkalian


In [41]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
B = np.array([
    [1,8,2],
    [2,1,1],
    [4,0,1]
])
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

**Penjumlahan**

In [44]:
A + B

array([[ 2, 10,  5],
       [ 6,  6,  7],
       [11,  8, 10]])

**Pengurangan**

In [46]:
A - B

array([[ 0, -6,  1],
       [ 2,  4,  5],
       [ 3,  8,  8]])

**Pembagian**

In [48]:
B / A

array([[1.        , 4.        , 0.66666667],
       [0.5       , 0.2       , 0.16666667],
       [0.57142857, 0.        , 0.11111111]])

**Perkalian**\

Three way
- matrix-scalar
- hadamard Product (*) / element wise
- matrix - matrix (@) / dot

In [51]:
# matrix-scalar
10*A

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [56]:
# hadamard product
print(A)

print(B)

A * B

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 8 2]
 [2 1 1]
 [4 0 1]]


array([[ 1, 16,  6],
       [ 8,  5,  6],
       [28,  0,  9]])

In [59]:
# Matrix-matrix multiplicaiton / @
# perhatikan rules yang harus dipenuhi!
# C(m,n) = A(m,k) . B(k,n)
A @ B

array([[17, 10,  7],
       [38, 37, 19],
       [59, 64, 31]])

In [64]:
# kalau shape beda
C = np.array([[2],[1],[5]])

C

array([[2],
       [1],
       [5]])

In [65]:
A @ C

array([[19],
       [43],
       [67]])

### Transpose

In [66]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Invers

- invers / det adanya di matrix square/persegi (m * m)..
- suatu matriks tidak memiliki invers jika nilai determinanya sama dengan 0

In [77]:
from numpy import array
from numpy.linalg import inv

In [78]:
inv(A)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

### Determinant
- invers / det adanya di matrix square/persegi (m * m)..
- untuk mengetahui apakah matrix memiliki invers atau tidak

In [79]:
from numpy import array
from numpy.linalg import det

In [80]:
det(A)

6.66133814775094e-16

### Contoh Soal!!

In [91]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

In [84]:
D = np.array([
    [1,2],
    [3,4]
])

D_adjecent = np.array([
    [4,-2],
    [-3,1]
])

In [86]:
inv_d = 1/det(D) * D_adjecent
inv_d

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [87]:
np.linalg.inv(D)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [92]:
np.linalg.det(A)

6.66133814775094e-16

ciri-ciri matriks determinan 0
- barisnya merupakan kelipatan dari baris yang lain
- contoh : 1,2,3  2,4,6
- barisnya merupakan kombinasi linear dari baris-baris yang ada

### Contoh Soal 2!!

In [93]:
E = np.array([
    [1,2,3],
    [2,4,6],
    [1,0,1]
])

In [94]:
np.linalg.det(E)

0.0

## Tensor

- vektor - 1D Array
- Matrix - 2D Array
- N-D - Array (3D dan seterusnya)

vektor = list
matrix = vektor dalam list
T-3D = matrix dalam list


In [95]:
x = np.array([
    [1,4,5,6],
    [4,3,7,1]
])

print(x)
print('')
print('shape: ',x.shape)

[[1 4 5 6]
 [4 3 7 1]]

shape:  (2, 4)


In [97]:
y = np.array([
    [2,8,8,1],
    [3,0,9,1]
])

print(y)
print('')
print('shape: ',y.shape)

[[2 8 8 1]
 [3 0 9 1]]

shape:  (2, 4)


In [98]:
z = np.array([
    [2,8,7,1],
    [3,0,10,1]
])

print(z)
print('')
print('shape: ',z.shape)

[[ 2  8  7  1]
 [ 3  0 10  1]]

shape:  (2, 4)


In [101]:
#Tensor

list_matrix = [x,y,z]
tensor = np.array(list_matrix)
tensor

array([[[ 1,  4,  5,  6],
        [ 4,  3,  7,  1]],

       [[ 2,  8,  8,  1],
        [ 3,  0,  9,  1]],

       [[ 2,  8,  7,  1],
        [ 3,  0, 10,  1]]])

In [104]:
tensor.shape

(3, 2, 4)