## Vektor

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
# Penjumlahan 2 buah list
list_1 = [1,2,3]
list_2 = [4,5,6]

list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [7]:
#penjumlahan 2 buah list setelah dirubah menjadi array
arr_1 = np.array(list_1)
arr_2 = np.array(list_2)

arr_1 + arr_2

array([5, 7, 9])

## Vector Norm (panjang vektor)

np.linalg.norm(v)

In [12]:
print(arr_1,arr_2)

[1 2 3] [4 5 6]


In [14]:
#vektor norm dari arr_1
np.linalg.norm(arr_1)

3.7416573867739413

In [16]:
#vektor nor dari arr_2
np.linalg.norm(arr_2)

8.774964387392123

In [23]:
# default : euclidean distance L2
arr = np.array([3,4])

np.linalg.norm(arr,2)

5.0

In [20]:
# distance manhattan L1
np.linalg.norm(arr,1)

7.0

## Operasi Aritmatika

### Penjumlahan

In [25]:
print(arr_1,arr_2)

[1 2 3] [4 5 6]


In [26]:
# penjumlahan vektor dengan skalar/bilangan
arr_1 + 10

array([11, 12, 13])

In [28]:
# penjumlahan vektor dengan vektor
arr_1 + arr_2

array([5, 7, 9])

In [30]:
# operasi aritmatika dilakukan dengan jumlah elemen yang sama
arr_3 = np.array([1,2,3,4,5])

arr_1 + arr_3


ValueError: operands could not be broadcast together with shapes (3,) (5,) 

### Penjumlahan

In [31]:
print(arr_1,arr_2)

[1 2 3] [4 5 6]


In [32]:
# pengurangan antara vektor dengan skalar / bilangan
arr_1 - 10

array([-9, -8, -7])

In [33]:
#pengurangan antara vektor dengan vektor
arr_1 - arr_2

array([-3, -3, -3])

### Pembagian

In [34]:
# pembagian vektor dengan skalar / bilangan
arr_1 / 2

array([0.5, 1. , 1.5])

In [35]:
# pembagian vektor dengan vektor
arr_1 / arr_2

array([0.25, 0.4 , 0.5 ])

### Perkalian

In [ ]:
# multiply by scalar
# multiply by vektor
# multiply by dot product

In [41]:
print(arr_1,arr_2)

[1 2 3] [4 5 6]


In [39]:
# perkalian vektro dengan skalar / bilangan
arr_1 * 10

array([10, 20, 30])

In [40]:
# perkalian vektor dengan vektor
arr_1 * arr_2

array([ 4, 10, 18])

In [45]:
# perkalian vektor dengan dot product # 1
arr_1.dot(arr_2)

32

In [46]:
# perkalian vektor dengan dot product # 2
np.dot(arr_1,arr_2)

32

In [47]:
# perkalian vektor dengan dot product # 3
arr_1 @ arr_2

32

## Cosine similarity

In [53]:
print(arr_1,arr_2)

[1 2 3] [4 5 6]


In [56]:
cos_theta = arr_1 @ arr_2 / (np.linalg.norm(arr_1) * np.linalg.norm(arr_2))
cos_theta

0.9746318461970762

#### Simulasi cosine similarity

In [65]:
#simulasi sudut 0 derajat
arr_3 = np.array([3,0])
arr_4 = np.array([5,0])

cos_theta = arr_3 @ arr_4 / (np.linalg.norm(arr_3) * np.linalg.norm(arr_4))
cos_theta

1.0

In [68]:
#simulasi sudut 90 derajat
arr_5 = np.array([0,4])
arr_6 = np.array([8,0])

cos_theta = arr_5 @ arr_6 / (np.linalg.norm(arr_5) * np.linalg.norm(arr_6))
cos_theta

0.0

In [72]:
# mencari sudut theta

# 1 convert ke bentuk radiant
rad = np.arccos(cos_theta)
rad


1.5707963267948966

In [71]:
# 2 convert radian ke bentuk degree / derajat
degree = np.degrees(rad)
degree

90.0

## Case study

- kalimat_1 = saya pergi ke rumah nenek saya
- kalimat_2 = saya pergi ke rumah kakek saya

In [ ]:
# melakukan mapping dari setiap kata unit yang ada
# 'saya' 'pergi' 'ke' 'rumah' 'nenek' 'saya'
# 'saya' 'pergi' 'ke' 'rumah' 'kakek' 'saya'
# kalimat | kal_1 | kal_2
# saya    | 2     | 2


In [74]:
kal_1 =[2,1,1,1,1,0]
kal_2 =[2,1,1,1,0,1]

In [76]:
kal_1 = np.array(kal_1)
kal_2 = np.array(kal_2)

print(kal_1,kal_2)

[2 1 1 1 1 0] [2 1 1 1 0 1]


In [78]:
cos_theta = kal_1 @ kal_2 / (np.linalg.norm(kal_1)* np.linalg.norm(kal_2))
cos_theta

0.8749999999999998

## Case Study 2
- kal_1 = saya kemarin pergi ke medan
- kal_2 = ibu saya sedang belanja

|mapping|kal_1|kal_2|
|-------|-----|-----|
| saya  | 1 | 1|
| kemarin | 1 | 0|
| pergi |1 | 0|
| ke |1 | 0 |
| medan | 1 | 0|
| ibu | 0 | 1 |
| sedang |0 | 1|
| belanja | 0 | 1

In [80]:
vek_1 = [1,1,1,1,1,0,0,0]
vek_2 = [1,0,0,0,0,1,1,1]

vek_1 = np.array(vek_1)
vek_2 = np.array(vek_2)

print(vek_1,vek_2)

[1 1 1 1 1 0 0 0] [1 0 0 0 0 1 1 1]


In [81]:
cos_theta = vek_1 @ vek_2 / (np.linalg.norm(vek_1)* np.linalg.norm(vek_2))
cos_theta

0.22360679774997896