# h8dsft_Linear_Algebra2

In [2]:
import numpy as np

### Soal 1
![Soal 1](https://raw.githubusercontent.com/sonnyrd/learning_journal/main/non_graded_challenge/phase0/data/img1.png)

creating matrix

In [5]:
a = np.array([
    [23,50],
    [7,12]
])

b = np.array([
    [57,67],
    [99,43]
])

c = np.array([
    [75,21],
    [57,12]
])

d = np.array([
    [87,26],
    [18,84]
])

create list matrix

In [8]:
list_matrix = [a,b,c,d]

create tensor

In [9]:
#tensor

tensor = np.array(list_matrix)

In [10]:
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

### Soal 2
![Soal 2](https://github.com/sonnyrd/learning_journal/blob/main/non_graded_challenge/phase0/data/img2.png?raw=true)

create matrix

In [11]:
A = np.array([
    [23,50,19],
    [7,12,109],
    [57,67,98]
])

B = np.array([
    [17],
    [22],
    [19]
])

Perkalian antar matrix

In [12]:
#cara 1
A @ B

array([[1852],
       [2454],
       [4305]])

In [13]:
#cara 2
A.dot(B)

array([[1852],
       [2454],
       [4305]])

### Soal 3
![Soal 3](https://github.com/sonnyrd/learning_journal/blob/main/non_graded_challenge/phase0/data/img3.png?raw=true)

import library

In [17]:
from numpy.linalg import det
from numpy.linalg import inv

create matrix

In [15]:
A = np.array([
    [23,50,19],
    [7,12,109],
    [57,67,98]
])

print(A)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


In [16]:
#Transpose
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [18]:
#Determinan
det(A)

131344.0000000002

In [19]:
#Invers
inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])