# h8dsft_Linear_Algebra3

import library

In [1]:
import numpy as np
from numpy.linalg import eig

# soal 1
![Soal 1](https://github.com/sonnyrd/learning_journal/blob/main/non_graded_challenge/phase0/data/img4.png?raw=true)

create matrix

In [2]:
a = np.array([
    [1,-1],
    [6,4]
])

In [24]:
a

array([[ 1, -1],
       [ 6,  4]])

create eigen value & eigen vector

In [9]:
eigval,eigvec = eig(a)

In [4]:
eigval

array([2.5+1.93649167j, 2.5-1.93649167j])

eigen value

In [25]:
#eigen value
np.argmax(eigval)

0

In [26]:
eigval[0]

(2.5+1.9364916731037083j)

In [35]:
#check!
# rumus A.eigvec = eigval.eigvec

np.dot(a,eigvec[:,0])

array([-1.15727512+0.29880715j,  2.31455025+1.79284291j])

In [36]:
np.dot(eigval[0],eigvec[:,0])

array([-1.15727512+0.29880715j,  2.31455025+1.79284291j])

In [37]:
print(np.allclose(np.dot(a,eigvec[:,0]),np.dot(eigval[0],eigvec[:,0])))



True


In [39]:
eigvec[:,0]

array([-0.23145502+0.29880715j,  0.9258201 +0.j        ])