# Numpy

In [5]:
import numpy as np

In [6]:
a= np.array([1,2,4])
a

array([1, 2, 4])

In [7]:
#perbedaan list dengan np

tinggi = [1.7, 1.8, 2.0]
berat = [65.5, 67.2, 59.2]

berat/tinggi 

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [18]:
tinggi = [1.7, 1.8, 2.0]
berat = [65.5, 67.2, 59.2]
np_tinggi = np.array(tinggi)
np_berat = np.array(berat)

np_berat/np_tinggi ** 2

array([22.66435986, 20.74074074, 14.8       ])

In [10]:
np.empty(5)

array([2.12199579e-314, 4.67296746e-307, 5.23709585e-321, 6.95229481e-310,
       3.91792377e-317])

In [20]:
np.arange(4,11,2)

array([ 4,  6,  8, 10])

In [30]:
arr = np.array([1,2,3,4])
arr = np.append(arr,[1,2,3])

In [31]:
np.sort(arr)

array([1, 1, 2, 2, 3, 3, 4])

In [34]:
np.delete(arr,2)

array([1, 2, 4, 1, 2, 3])

In [36]:
# 0 Dimensi / skalar
arr = np.array(4)
print(arr)

4


In [37]:
# 1 Dimensi / vektor
arr = np.array([4,2,3])
print(arr)

[4 2 3]


In [41]:
# 2 dimensi / matriks
arr = np.array([[4,2,3],[5,6,7]])
print(arr)

[[4 2 3]
 [5 6 7]]


In [48]:
arr.shape

(2, 3)

In [51]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [45]:
#pengecekan jumlah dimensi
array_example.ndim

3

In [52]:
 array_example.shape

(3, 2, 4)

In [55]:
array_example.size

24

In [62]:
#reshape
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [69]:
matriks = a.reshape(3,2)
print(matriks)

[[0 1]
 [2 3]
 [4 5]]


In [72]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [74]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [81]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [83]:
# for a column vector, You can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [84]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [87]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [88]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Slicing

In [92]:
#Soal

arr = np.array([2,3,7,8,9])
print(arr[2:5])

[7 8 9]


In [97]:
print(arr[2:5:3])
#index ke 2[7] sampai ke [9] dengan 3 step

[7]


In [99]:
print(arr[::2])

[2 7 9]


In [101]:
print(arr[:3:2])

[2 7]


In [128]:
#Soal

arr = np.array([[2,3,7,8,9],[1,3,6,8,4]])
print(arr[1,1:4])

[3 6 8]


In [133]:
print(arr[0:2,4])

[9 4]


In [141]:
print(arr[0])
print(arr[1])

print(arr[0:2])

[2 3 7 8 9]
[1 3 6 8 4]
[[2 3 7 8 9]
 [1 3 6 8 4]]


In [148]:
#Soal

arr = np.array([[2,3,7,8,9],[1,3,6,8,4],[1,3,6,8,4]])
print(arr[1:2,2:4])

[[6 8]]


In [150]:
print(arr[1:3,2:4])

[[6 8]
 [6 8]]


In [155]:
#Soal

a = np.array([[2,3,7,8,9],[1,3,6,8,4],[1,3,6,8,4]])
print(a[a>=5])

[7 8 9 6 8 6 8]


In [157]:
a1 = np.array([[1,2],[3,4]])

a2 = np.array([[1,2],[3,4]])


In [160]:
np.vstack([a1,a2])

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [162]:
np.hstack([a1,a2])

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [163]:
data_1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [181]:
# -1 unknown dimenssion
new_data_1 = data_1.reshape(2,2,-1)
print(new_data_1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [183]:
new_data_1.ndim

3