In [2]:
import numpy as np
import pandas as pd

In [27]:
pd.Series([4.5,2.0,3.1])

0    4.5
1    2.0
2    3.1
dtype: float64

In [28]:
pd.Series(['a','b','c'])

0    a
1    b
2    c
dtype: object

In [29]:
pd.Series(['a','b','c',4,5])

0    a
1    b
2    c
3    4
4    5
dtype: object

In [30]:
revenues = pd.Series([5555, 7000, 1980])

In [31]:
revenues

0    5555
1    7000
2    1980
dtype: int64

In [33]:
revenues.values

array([5555, 7000, 1980], dtype=int64)

In [34]:
revenues.index

RangeIndex(start=0, stop=3, step=1)

In [18]:
#pd.serius([value],index=["listindex"]))

city_revenues = pd.Series(
    [4200, 8000, 6500],
    index=["Amsterdam", "Toronto", "Tokyo"]
)
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [20]:
city_employee_count = pd.Series({"Amsterdam": 5, "Tokyo": 8})
city_employee_count

Amsterdam    5
Tokyo        8
dtype: int64

In [22]:
city_employee_count.keys()

Index(['Amsterdam', 'Tokyo'], dtype='object')

In [24]:
"Tokyo" in city_employee_count

True

In [25]:
"New York" in city_employee_count

False

In [37]:
city_employee_count.values

array([5, 8], dtype=int64)

In [39]:
8 in city_employee_count.values

True

In [ ]:
#city_data = pd.DataFrame({
#    "nama kolom 1" : value kolom 1,
#    "nama kolom 2" : value di kolom 2
#})

In [40]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [42]:
city_employee_count

Amsterdam    5
Tokyo        8
dtype: int64

In [44]:
city_data = pd.DataFrame({
    "revenue" : city_revenues,
    "employee_count" : city_employee_count
})

In [46]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [49]:
city_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Amsterdam to Toronto
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   revenue         3 non-null      int64  
 1   employee_count  2 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 72.0+ bytes


In [50]:
city_data.index

Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object')

In [51]:
city_data.values

array([[4.2e+03, 5.0e+00],
       [6.5e+03, 8.0e+00],
       [8.0e+03,     nan]])

In [53]:
city_data.columns

Index(['revenue', 'employee_count'], dtype='object')

In [55]:
city_data.axes

[Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object'),
 Index(['revenue', 'employee_count'], dtype='object')]

In [57]:
city_data.axes[0]

Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object')

In [61]:
city_data.axes[1]

Index(['revenue', 'employee_count'], dtype='object')

In [62]:
city_data.keys()

Index(['revenue', 'employee_count'], dtype='object')

In [63]:
"employee_count" in city_data

True

### Accesing series elements

In [65]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [67]:
city_revenues["Toronto"]

8000

In [69]:
city_revenues[1]

8000

In [70]:
city_revenues[-1]

6500

In [74]:
city_revenues[1:]

Toronto    8000
Tokyo      6500
dtype: int64

In [75]:
city_revenues["Toronto":]

Toronto    8000
Tokyo      6500
dtype: int64

### Using .loc and .iloc

In [77]:
colors = pd.Series(
    ["red", "purple", "blue", "green", "yellow"],
    index=[1, 2, 3, 5, 8]
)

In [87]:
colors

1       red
2    purple
3      blue
5     green
8    yellow
dtype: object

In [88]:
colors[1]

'red'

In [85]:
# .loc refer to the label index
# .iloc refer to the positional index (0,1,2,3,4)

colors.loc[1]

'red'

In [89]:
colors.iloc[1]

'purple'

In [91]:
colors

1       red
2    purple
3      blue
5     green
8    yellow
dtype: object

In [98]:
#return the element with the implicit index : 1 , 2
colors.iloc[0:5:3]

1      red
5    green
dtype: object

In [100]:
colors.iloc[[1,4]]

2    purple
8    yellow
dtype: object

In [97]:
#return the element with the explicit index between 3 and 8
colors.loc[3:8]

3      blue
5     green
8    yellow
dtype: object

In [101]:
colors.loc[[1,2,3]]

1       red
2    purple
3      blue
dtype: object

In [103]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [127]:
city_revenues.loc['Toronto']

8000

In [128]:
city_revenues.loc[['Toronto','Tokyo']]

Toronto    8000
Tokyo      6500
dtype: int64

## Accesing DataFrame Elements

In [114]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [116]:
city_data['revenue']

Amsterdam    4200
Tokyo        6500
Toronto      8000
Name: revenue, dtype: int64

In [124]:
city_data[['revenue','employee_count']]

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [118]:
city_data.revenue

Amsterdam    4200
Tokyo        6500
Toronto      8000
Name: revenue, dtype: int64

In [119]:
toys = pd.DataFrame([
    {"name": "ball", "shape": "sphere"},
    {"name": "Rubik's cube", "shape": "cube"}
])

In [122]:
toys['shape']

0    sphere
1      cube
Name: shape, dtype: object

In [123]:
toys.shape

(2, 2)

### DataFrame using .loc and .iloc

In [130]:
city_data.loc['Amsterdam']

revenue           4200.0
employee_count       5.0
Name: Amsterdam, dtype: float64

In [133]:
city_data.loc['Tokyo':'Toronto']

revenue  employee_count
Tokyo       6500             8.0
Toronto     8000             NaN

In [137]:
city_data.loc[['Toronto','Tokyo']]

revenue  employee_count
Toronto     8000             NaN
Tokyo       6500             8.0

In [142]:
city_data.iloc[0]

revenue           4200.0
employee_count       5.0
Name: Amsterdam, dtype: float64

In [143]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [146]:
city_data.loc["Amsterdam":"Tokyo","employee_count"]

Amsterdam    5.0
Tokyo        8.0
Name: employee_count, dtype: float64

In [148]:
city_revenues.sum()

18700

In [150]:
city_revenues.max()

8000

In [151]:
city_revenues.min()

4200

In [152]:
city_revenues.mean()

6233.333333333333

### Filter Pandas DataFrame with numpy

### Combining Multiple Datasets

In [153]:
further_city_data = pd.DataFrame(
    {"revenue": [7000, 3400], "employee_count": [2, 2]},
    index=["New York", "Barcelona"]
)

In [154]:
further_city_data

revenue  employee_count
New York      7000               2
Barcelona     3400               2

In [155]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [164]:
# .concat():
# Contoh memanjang ke bawah 

all_city_data = pd.concat([city_data,further_city_data], sort=False)

In [165]:
all_city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN
New York      7000             2.0
Barcelona     3400             2.0

In [167]:
# .concat(): secara horizontal


In [169]:
city_countries = pd.DataFrame({
    "country": ["Holland", "Japan", "Holland", "Canada", "Spain"],
    "capital": [1, 1, 0, 0, 0]},
    index=["Amsterdam", "Tokyo", "Rotterdam", "Toronto", "Barcelona"]
)

In [172]:
all_city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN
New York      7000             2.0
Barcelona     3400             2.0

In [170]:
city_countries

country  capital
Amsterdam  Holland        1
Tokyo        Japan        1
Rotterdam  Holland        0
Toronto     Canada        0
Barcelona    Spain        0

In [178]:
#axis=0 baris, Axis=1 kolom
cities = pd.concat([all_city_data, city_countries], axis=1, sort=False)

In [179]:
cities

revenue  employee_count  country  capital
Amsterdam   4200.0             5.0  Holland      1.0
Tokyo       6500.0             8.0    Japan      1.0
Toronto     8000.0             NaN   Canada      0.0
New York    7000.0             2.0      NaN      NaN
Barcelona   3400.0             2.0    Spain      0.0
Rotterdam      NaN             NaN  Holland      0.0

In [180]:
#dapat dihilat Pandas menambahkan NaN for the missing values
# if you want to combine only the cities that appear in bot DataFrame object, 
# #then you can set the join parameter to inner

In [181]:
pd.concat([all_city_data,city_countries], axis=1, join="inner")

revenue  employee_count  country  capital
Amsterdam     4200             5.0  Holland        1
Tokyo         6500             8.0    Japan        1
Toronto       8000             NaN   Canada        0
Barcelona     3400             2.0    Spain        0

In [ ]:
### .concat() mengacu kepada index
### .merge() mengacu berdasarkan kolom

In [183]:
countries = pd.DataFrame({
    "population_millions": [17, 127, 37],
    "continent": ["Europe", "Asia", "North America"]
}, index=["Holland", "Japan", "Canada"])

In [184]:
countries

population_millions      continent
Holland                   17         Europe
Japan                    127           Asia
Canada                    37  North America

In [185]:
cities

revenue  employee_count  country  capital
Amsterdam   4200.0             5.0  Holland      1.0
Tokyo       6500.0             8.0    Japan      1.0
Toronto     8000.0             NaN   Canada      0.0
New York    7000.0             2.0      NaN      NaN
Barcelona   3400.0             2.0    Spain      0.0
Rotterdam      NaN             NaN  Holland      0.0

In [190]:
pd.merge(cities, countries, left_on="country", right_index=True)

revenue  employee_count  country  capital  population_millions  \
Amsterdam   4200.0             5.0  Holland      1.0                   17   
Rotterdam      NaN             NaN  Holland      0.0                   17   
Tokyo       6500.0             8.0    Japan      1.0                  127   
Toronto     8000.0             NaN   Canada      0.0                   37   

               continent  
Amsterdam         Europe  
Rotterdam         Europe  
Tokyo               Asia  
Toronto    North America

In [192]:
cities

revenue  employee_count  country  capital
Amsterdam   4200.0             5.0  Holland      1.0
Tokyo       6500.0             8.0    Japan      1.0
Toronto     8000.0             NaN   Canada      0.0
New York    7000.0             2.0      NaN      NaN
Barcelona   3400.0             2.0    Spain      0.0
Rotterdam      NaN             NaN  Holland      0.0

In [197]:
countries

population_millions      continent
Holland                   17         Europe
Japan                    127           Asia
Canada                    37  North America

In [196]:
pd.merge(
    cities,
    countries,
    left_on="country",
    right_index=True,
    how="left"
)

revenue  employee_count  country  capital  population_millions  \
Amsterdam   4200.0             5.0  Holland      1.0                 17.0   
Tokyo       6500.0             8.0    Japan      1.0                127.0   
Toronto     8000.0             NaN   Canada      0.0                 37.0   
New York    7000.0             2.0      NaN      NaN                  NaN   
Barcelona   3400.0             2.0    Spain      0.0                  NaN   
Rotterdam      NaN             NaN  Holland      0.0                 17.0   

               continent  
Amsterdam         Europe  
Tokyo               Asia  
Toronto    North America  
New York             NaN  
Barcelona            NaN  
Rotterdam         Europe